# countries = [
#     'Norway',
#     'Spain',
#     'France',
#     'Netherlands',
#     'Czechia',
#     'Germany',
#     'Austria',
#     'Switzerland',
#     'United Kingdom of Great Britain and Northern Ireland',
#     'Italy',
#     'Greece',
#     'Ireland',
#     'Denmark',
#     'Portugal',
#     'Sweden',
#     'Belgium',
#     'Finland',
#     'Poland',
#     'Romania',
#     'Luxembourg',
#     'Bulgaria',
#     'Ukraine',
#     'Moldova (Republic of)',
#     'Slovakia',
#     'Estonia',
#     'Croatia',
#     'Albania',
#     'Hungary',
#     'Lithuania',
#     'Malta',
#     'Cyprus',
#     'Serbia',
#     'Iceland',
#     'Slovenia',
#     'North Macedonia',
#     'Liechtenstein',
#     'Jersey',
#     'Bosnia and Herzegovina',
#     'Azerbaijan',
#     'Belarus',
#     'San Marino',
#     'Montenegro',
#     'Andorra',
#     'Faroe Islands'
# ]

countries = ['Canada', 'Singapour', 'Australia']
